Lots of changes: include proprietary Qualcomm blobs in a little sysroot of their own, allows camera and audio to work. Update test program to be a menu of options controllable with wheels and button. Include rsync, htop, and fix sftp. Allow install script to work in a dev recovery partition. Disable msm_thermal driver and set CPU/RAM frequencies to maximum.

diff --git a/mdm-init/wlan_ipc/wlan b/mdm-init/wlan_ipc/wlan
--- a/mdm-init/wlan_ipc/wlan
+++ b/mdm-init/wlan_ipc/wlan
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright (c) 2017, The Linux Foundation. All rights reserved.
+# Copyright (c) 2013-2015, The Linux Foundation. All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are
@@ -27,19 +27,17 @@
 # OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
 # IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# add wake lock
-echo softAP_wakeLock > /sys/power/wake_lock
-
 export MODULE_BASE=/lib/modules/`uname -r`
 export RETRY_LIMIT=3
 HELP="Usage $0 {start | stop | restart} <ap | sta,ap>"
 DUMP_TO_KMSG=/dev/kmsg
-serialno=`cat /sys/devices/virtual/android_usb/android0/iSerial`
+WLAN_CONF_FILE=/data/misc/wifi/wlan_mode
 
+#by default, softAP mode will be choosed
 do_ctrl_cld_ll () {
     case "$1" in
     start)
-        echo "Starting IPC WLAN... $@" > $DUMP_TO_KMSG
+        echo "Starting WLAN... $@" > $DUMP_TO_KMSG
         shift
         start_ap1=0
         if [ "$1" == "ap,ap" ] || [ "$1" == "sta,ap" ]; then
@@ -50,35 +48,70 @@ do_ctrl_cld_ll () {
         elif [ "$1" == "ap,sta" ]; then
             return 1
         fi
-        if [ -f /persist/wlan_mac ]; then
-            macaddress=`cat /persist/wlan_mac`
-            if [ -f /sys/devices/soc.0/a000000.qcom,wcnss-wlan/wcnss_mac_addr ]; then
-                echo  $macaddress > /sys/devices/soc.0/a000000.qcom,wcnss-wlan/wcnss_mac_addr
-            fi
+
+#        set -e
+        insmod $MODULE_BASE/extra/wlan.ko con_mode=1
+#        set +e
+
+        c=1
+        ifconfig wlan0 up 2>  /dev/null
+        rc=$?
+        while [ $rc -ne 0 -a $c -le $RETRY_LIMIT ]; do
+            sleep 1
+            ifconfig wlan0 up 2> /dev/null
+            rc=$?
+            c=`expr $c + 1`
+        done
+
+        if [ $c -gt $RETRY_LIMIT ]; then
+            echo "WLAN bring-up failed!" > $DUMP_TO_KMSG
+            exit 1
         fi
-        if [ -f /sys/bus/platform/drivers/wcnss_wlan/a000000.qcom,wcnss-wlan/serial_number ]; then
-            echo $serialno > /sys/bus/platform/drivers/wcnss_wlan/a000000.qcom,wcnss-wlan/serial_number
+
+        if [ $start_ap1 -eq 1 ]; then
+            echo "Adding second AP interface(wlan1)" > $DUMP_TO_KMSG
+            iw dev wlan0 interface add wlan1 type __ap
+            ifconfig wlan1 up 2> /dev/null
+            return $?
         fi
 
-        echo "Starting PTT Socket App... $@" > $DUMP_TO_KMSG
-        /usr/bin/ptt_socket_app -d &
+        mode="client"
+        if [ -f "$WLAN_CONF_FILE" ]; then
+            read mode < $WLAN_CONF_FILE
+        fi
 
-        set -e
-        insmod $MODULE_BASE/extra/wlan.ko $@
-        set +e
+        echo "Wlan bootup mode is $mode" > $DUMP_TO_KMSG
 
-        echo "Starting ipc services ..." > $DUMP_TO_KMSG
-	/etc/init.d/ipc-startup.sh
+        if [ "$mode" == "softap" ] || [ "$mode" == "ap" ] || [ "$mode" == "sap" ]; then
+            #start_ap
+            echo "Starting hostapd and DHCP server" > $DUMP_TO_KMSG
+            hostapd /data/misc/wifi/hostapd.conf &
+            ifconfig wlan0 192.168.1.1 netmask 255.255.255.0 up
+            killall -9 dnsmasq
+            dnsmasq -i wlan0 --dhcp-range=192.168.1.10,192.168.1.100,12h --dhcp-leasefile=/data/dnsmasq_d.leases
 
+            return $?
+        fi
+
+        #start_sta
+        echo "Starting STA and DHCP client" > $DUMP_TO_KMSG
+        wpa_supplicant -Dnl80211 -iwlan0 -c /data/misc/wifi/wpa_supplicant.conf&
+        /usr/sbin/dhcpcd wlan0 -t 0 -o domain_name_servers --noipv4ll -h -b
         ;;
 
     start_ftm)
-        echo "Starting IPC WLAN in FTM Mode ..." > $DUMP_TO_KMSG
-        insmod $MODULE_BASE/extra/wlan.ko con_mode=5
+        do_ctrl_cld_ll start con_mode=5
         ;;
 
     stop)
         echo "Stopping WLAN..." > $DUMP_TO_KMSG
+        ps -e | grep 'dnsmasq -i wlan0 --dhcp-range=192.168.1.10,192.168.1.100,12h --dhcp-leasefile=/data/dnsmasq_d.leases'|grep -v grep
+        if [ $? -eq 0 ]; then
+            killall -9 dnsmasq
+        fi
+        killall -9 hostapd
+        killall -9 wpa_supplicant
+        killall -9 dhcpcd
         rmmod wlan
         ;;
 
@@ -101,10 +134,7 @@ do_ctrl_cld_ll () {
 do_ctrl_cld_ll $@
 if [ $? -ne 0 ]; then
     echo $HELP >&2
-    echo softAP_wakeLock > /sys/power/wake_unlock
     exit 1
 fi
-
-echo softAP_wakeLock > /sys/power/wake_unlock
 
 exit 0
